### ISSUE TITLE
Any reason this would stop working with RN 0.36

### ISSUE THREAD

**Issue by indivisable** [obipawan/react-native-hyperlink#8]
I have used this for past few months but recently (as of yesterday) it became a lot less reliable. Not sure if this is because of an update or something else but now when I tap the links it only works like 25% of the times and it used to work all the time.

**Comment by obipawan** [comment]
That's weird. The update you're talking about, is it this library or react
native?
There was an update with hyperlink couple of weeks back for links
actionable on long clicks, so maybe there's a bug due to an oversight.. If
so could you try using 0.0.7?
If it was react native itself (0.36), I'll have a look in about a week's
time (on vacation :) )
In the meantime, if you could share something reproducible, that'd be
great. Thanks!

**Comment by indivisable** [comment]
It seems it may be with RN 0.36 as I tried using Text onPress={} and similar issue. I will try to reproduce but I tested against a similar library (react-native-autolink and plain Text) and got same results so I'll close it for now.
